# Generated by Django 5.1.2 on 2024-10-25 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(choices=[('KITCHEN', 'kitchen'), ('CLEANING', 'cleaning'), ('GARDENING', 'gardening'), ('LIBRARY', 'library'), ('LAUNDRY', 'laundry')], default='No Work Assigned', max_length=10)),
                ('date', models.DateField()),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='home.inmate')),
            ],
        ),
    ]
