# Generated by Django 5.1.2 on 2024-10-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_guard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guard',
        ),
        migrations.AddField(
            model_name='report',
            name='reported_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
