# Generated by Django 5.1.2 on 2024-10-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_guard_report_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='reported_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
