# Generated by Django 5.1.2 on 2024-10-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_work_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='admin_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
